# Generated by Django 6.0.2 on 2026-02-26 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(max_length=200)),
                ('office_hospital', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('user_position', models.CharField(max_length=200)),
                ('computer_name', models.CharField(max_length=200)),
                ('assigned_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('processor', models.CharField(blank=True, max_length=200)),
                ('motherboard', models.CharField(blank=True, max_length=200)),
                ('ssd', models.CharField(blank=True, max_length=200)),
                ('hdd', models.CharField(blank=True, max_length=200)),
                ('ram', models.CharField(blank=True, max_length=200)),
                ('gpu', models.CharField(blank=True, max_length=200)),
                ('psu', models.CharField(blank=True, max_length=200)),
                ('case', models.CharField(blank=True, max_length=200)),
                ('monitor', models.CharField(blank=True, max_length=200)),
                ('keyboard', models.CharField(blank=True, max_length=200)),
                ('mouse', models.CharField(blank=True, max_length=200)),
                ('avr', models.CharField(blank=True, max_length=200)),
                ('ups', models.CharField(blank=True, max_length=200)),
                ('webcam', models.CharField(blank=True, max_length=200)),
                ('printer', models.CharField(blank=True, max_length=200)),
                ('antivirus', models.CharField(blank=True, max_length=200)),
                ('ms_office', models.CharField(blank=True, max_length=200)),
                ('operating_system', models.CharField(blank=True, max_length=200)),
                ('other_software', models.CharField(blank=True, max_length=200)),
                ('replacement_details', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('date_received', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
