# Generated by Django 6.0.2 on 2026-03-09 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='antivirus',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='avr',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='case',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='gpu',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='hdd',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='keyboard',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='monitor',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='motherboard',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='mouse',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='ms_office',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='other_software',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='printer',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='processor',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='psu',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='replacement_details',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='ssd',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='ups',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='webcam',
        ),
        migrations.CreateModel(
            name='EquipmentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(choices=[('Processor', 'Processor'), ('Motherboard', 'Motherboard'), ('Solid State Drive (SSD)', 'Solid State Drive (SSD)'), ('Hard Disk Drive (HDD)', 'Hard Disk Drive (HDD)'), ('Memory Card 1', 'Memory (RAM) 1'), ('Memory Card 2', 'Memory (RAM) 2'), ('Video Card', 'Video Card'), ('Power Supply Unit', 'Power Supply'), ('CPU Case', 'CPU Case'), ('Monitor', 'Monitor'), ('Keyboard', 'Keyboard'), ('Mouse', 'Mouse'), ('Automatic Voltage Regulator', 'Automatic Voltage Regulator'), ('Uninterruptible Power Supply', 'Uninterruptible Power Supply'), ('Webcam', 'Webcam'), ('Printer', 'Printer'), ('Antivirus Software', 'Antivirus Software'), ('MS Office', 'MS Office'), ('Operating System', 'Operating System'), ('Application Software', 'Application Software')], max_length=100)),
                ('original_model', models.CharField(blank=True, max_length=200)),
                ('original_serial', models.CharField(blank=True, max_length=200)),
                ('replacement_model', models.CharField(blank=True, max_length=200)),
                ('replacement_serial', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='inventory.inventory')),
            ],
        ),
    ]
