# Generated by Django 6.0.2 on 2026-03-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventory_antivirus_remove_inventory_avr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
