# Generated by Django 6.0.2 on 2026-03-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
