# Generated by Django 6.0.2 on 2026-03-11 03:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='user_position',
            new_name='position',
        ),
        migrations.AddField(
            model_name='inventory',
            name='received_by',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='assigned_ip',
            field=models.CharField(max_length=200),
        ),
    ]
