# Generated by Django 6.0.2 on 2026-03-11 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_user_position_inventory_position_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='office_hospital',
            new_name='office_or_hospital',
        ),
    ]
