# Generated by Django 6.0.2 on 2026-03-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_office_hospital_inventory_office_or_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateField(),
        ),
    ]
