# Generated by Django 6.0.2 on 2026-03-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_alter_inventory_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("Maintenance", "Maintenance"),
                    ("Condemned", "Condemned"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
    ]

